/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as WalletRouteImport } from './pages/wallet'
import { Route as TermsRouteImport } from './pages/terms'
import { Route as SettingsRouteImport } from './pages/settings'
import { Route as SessionRouteImport } from './pages/session'
import { Route as ReviewRouteImport } from './pages/review'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as PrivacyRouteImport } from './pages/privacy'
import { Route as PaymentRouteImport } from './pages/payment'
import { Route as OtpRouteImport } from './pages/otp'
import { Route as NotificationsRouteImport } from './pages/notifications'
import { Route as MyRatingRouteImport } from './pages/my-rating'
import { Route as ManageAddressesRouteImport } from './pages/manage-addresses'
import { Route as LoginRouteImport } from './pages/login'
import { Route as HomeRouteImport } from './pages/home'
import { Route as FaqRouteImport } from './pages/faq'
import { Route as ExploreRouteImport } from './pages/explore'
import { Route as EmergencyRouteImport } from './pages/emergency'
import { Route as ConfirmedRouteImport } from './pages/confirmed'
import { Route as ChatbotRouteImport } from './pages/chatbot'
import { Route as ChatRouteImport } from './pages/chat'
import { Route as BookingsRouteImport } from './pages/bookings'
import { Route as AdminRouteImport } from './pages/admin'
import { Route as AboutRouteImport } from './pages/about'
import { Route as ProviderIndexRouteImport } from './pages/Provider/index'
import { Route as CompanionIdRouteImport } from './pages/companion.$id'
import { Route as CategoryNameRouteImport } from './pages/category.$name'
import { Route as BookIdRouteImport } from './pages/book.$id'
import { Route as ProviderWithdrawRouteImport } from './pages/Provider/withdraw'
import { Route as ProviderTermsRouteImport } from './pages/Provider/terms'
import { Route as ProviderSplashRouteImport } from './pages/Provider/splash'
import { Route as ProviderSessionRouteImport } from './pages/Provider/session'
import { Route as ProviderSafetyGuidelinesRouteImport } from './pages/Provider/safety-guidelines'
import { Route as ProviderReviewsRouteImport } from './pages/Provider/reviews'
import { Route as ProviderProfileRouteImport } from './pages/Provider/profile'
import { Route as ProviderPrivacyRouteImport } from './pages/Provider/privacy'
import { Route as ProviderPerformanceRouteImport } from './pages/Provider/performance'
import { Route as ProviderNotificationsRouteImport } from './pages/Provider/notifications'
import { Route as ProviderMoreRouteImport } from './pages/Provider/more'
import { Route as ProviderHomeRouteImport } from './pages/Provider/home'
import { Route as ProviderHelpCenterRouteImport } from './pages/Provider/help-center'
import { Route as ProviderFeedbackRouteImport } from './pages/Provider/feedback'
import { Route as ProviderEmergencyContactsRouteImport } from './pages/Provider/emergency-contacts'
import { Route as ProviderEarningsRouteImport } from './pages/Provider/earnings'
import { Route as ProviderCommissionDetailsRouteImport } from './pages/Provider/commission-details'
import { Route as ProviderCodeOfConductRouteImport } from './pages/Provider/code-of-conduct'
import { Route as ProviderChatRouteImport } from './pages/Provider/chat'
import { Route as ProviderBookingsRouteImport } from './pages/Provider/bookings'
import { Route as ProviderBlockedCustomersRouteImport } from './pages/Provider/blocked-customers'
import { Route as ProviderBankAccountsRouteImport } from './pages/Provider/bank-accounts'
import { Route as ProviderAvailabilityRouteImport } from './pages/Provider/availability'
import { Route as ProviderApprovalRouteImport } from './pages/Provider/approval'
import { Route as ProviderSessionCompleteRouteImport } from './pages/Provider/session.complete'
import { Route as ProviderProfilePreviewRouteImport } from './pages/Provider/profile.preview'
import { Route as ProviderBookingIdRouteImport } from './pages/Provider/booking.$id'
import { Route as ProviderAuthVerifyRouteImport } from './pages/Provider/auth/verify'
import { Route as ProviderAuthServicesRouteImport } from './pages/Provider/auth/services'
import { Route as ProviderAuthPricingRouteImport } from './pages/Provider/auth/pricing'
import { Route as ProviderAuthPhoneRouteImport } from './pages/Provider/auth/phone'
import { Route as ProviderAuthOtpRouteImport } from './pages/Provider/auth/otp'
import { Route as ProviderAuthDetailsRouteImport } from './pages/Provider/auth/details'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRatingRoute = MyRatingRouteImport.update({
  id: '/my-rating',
  path: '/my-rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAddressesRoute = ManageAddressesRouteImport.update({
  id: '/manage-addresses',
  path: '/manage-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/Provider/',
  path: '/Provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionIdRoute = CompanionIdRouteImport.update({
  id: '/companion/$id',
  path: '/companion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderWithdrawRoute = ProviderWithdrawRouteImport.update({
  id: '/Provider/withdraw',
  path: '/Provider/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderTermsRoute = ProviderTermsRouteImport.update({
  id: '/Provider/terms',
  path: '/Provider/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSplashRoute = ProviderSplashRouteImport.update({
  id: '/Provider/splash',
  path: '/Provider/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSessionRoute = ProviderSessionRouteImport.update({
  id: '/Provider/session',
  path: '/Provider/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSafetyGuidelinesRoute =
  ProviderSafetyGuidelinesRouteImport.update({
    id: '/Provider/safety-guidelines',
    path: '/Provider/safety-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderReviewsRoute = ProviderReviewsRouteImport.update({
  id: '/Provider/reviews',
  path: '/Provider/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderProfileRoute = ProviderProfileRouteImport.update({
  id: '/Provider/profile',
  path: '/Provider/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderPrivacyRoute = ProviderPrivacyRouteImport.update({
  id: '/Provider/privacy',
  path: '/Provider/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderPerformanceRoute = ProviderPerformanceRouteImport.update({
  id: '/Provider/performance',
  path: '/Provider/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderNotificationsRoute = ProviderNotificationsRouteImport.update({
  id: '/Provider/notifications',
  path: '/Provider/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderMoreRoute = ProviderMoreRouteImport.update({
  id: '/Provider/more',
  path: '/Provider/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderHomeRoute = ProviderHomeRouteImport.update({
  id: '/Provider/home',
  path: '/Provider/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderHelpCenterRoute = ProviderHelpCenterRouteImport.update({
  id: '/Provider/help-center',
  path: '/Provider/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderFeedbackRoute = ProviderFeedbackRouteImport.update({
  id: '/Provider/feedback',
  path: '/Provider/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderEmergencyContactsRoute =
  ProviderEmergencyContactsRouteImport.update({
    id: '/Provider/emergency-contacts',
    path: '/Provider/emergency-contacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderEarningsRoute = ProviderEarningsRouteImport.update({
  id: '/Provider/earnings',
  path: '/Provider/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderCommissionDetailsRoute =
  ProviderCommissionDetailsRouteImport.update({
    id: '/Provider/commission-details',
    path: '/Provider/commission-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderCodeOfConductRoute = ProviderCodeOfConductRouteImport.update({
  id: '/Provider/code-of-conduct',
  path: '/Provider/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderChatRoute = ProviderChatRouteImport.update({
  id: '/Provider/chat',
  path: '/Provider/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/Provider/bookings',
  path: '/Provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBlockedCustomersRoute =
  ProviderBlockedCustomersRouteImport.update({
    id: '/Provider/blocked-customers',
    path: '/Provider/blocked-customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProviderBankAccountsRoute = ProviderBankAccountsRouteImport.update({
  id: '/Provider/bank-accounts',
  path: '/Provider/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAvailabilityRoute = ProviderAvailabilityRouteImport.update({
  id: '/Provider/availability',
  path: '/Provider/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderApprovalRoute = ProviderApprovalRouteImport.update({
  id: '/Provider/approval',
  path: '/Provider/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSessionCompleteRoute = ProviderSessionCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ProviderSessionRoute,
} as any)
const ProviderProfilePreviewRoute = ProviderProfilePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProviderProfileRoute,
} as any)
const ProviderBookingIdRoute = ProviderBookingIdRouteImport.update({
  id: '/Provider/booking/$id',
  path: '/Provider/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthVerifyRoute = ProviderAuthVerifyRouteImport.update({
  id: '/Provider/auth/verify',
  path: '/Provider/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthServicesRoute = ProviderAuthServicesRouteImport.update({
  id: '/Provider/auth/services',
  path: '/Provider/auth/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthPricingRoute = ProviderAuthPricingRouteImport.update({
  id: '/Provider/auth/pricing',
  path: '/Provider/auth/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthPhoneRoute = ProviderAuthPhoneRouteImport.update({
  id: '/Provider/auth/phone',
  path: '/Provider/auth/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthOtpRoute = ProviderAuthOtpRouteImport.update({
  id: '/Provider/auth/otp',
  path: '/Provider/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderAuthDetailsRoute = ProviderAuthDetailsRouteImport.update({
  id: '/Provider/auth/details',
  path: '/Provider/auth/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/chatbot': typeof ChatbotRoute
  '/confirmed': typeof ConfirmedRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/manage-addresses': typeof ManageAddressesRoute
  '/my-rating': typeof MyRatingRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/Provider/approval': typeof ProviderApprovalRoute
  '/Provider/availability': typeof ProviderAvailabilityRoute
  '/Provider/bank-accounts': typeof ProviderBankAccountsRoute
  '/Provider/blocked-customers': typeof ProviderBlockedCustomersRoute
  '/Provider/bookings': typeof ProviderBookingsRoute
  '/Provider/chat': typeof ProviderChatRoute
  '/Provider/code-of-conduct': typeof ProviderCodeOfConductRoute
  '/Provider/commission-details': typeof ProviderCommissionDetailsRoute
  '/Provider/earnings': typeof ProviderEarningsRoute
  '/Provider/emergency-contacts': typeof ProviderEmergencyContactsRoute
  '/Provider/feedback': typeof ProviderFeedbackRoute
  '/Provider/help-center': typeof ProviderHelpCenterRoute
  '/Provider/home': typeof ProviderHomeRoute
  '/Provider/more': typeof ProviderMoreRoute
  '/Provider/notifications': typeof ProviderNotificationsRoute
  '/Provider/performance': typeof ProviderPerformanceRoute
  '/Provider/privacy': typeof ProviderPrivacyRoute
  '/Provider/profile': typeof ProviderProfileRouteWithChildren
  '/Provider/reviews': typeof ProviderReviewsRoute
  '/Provider/safety-guidelines': typeof ProviderSafetyGuidelinesRoute
  '/Provider/session': typeof ProviderSessionRouteWithChildren
  '/Provider/splash': typeof ProviderSplashRoute
  '/Provider/terms': typeof ProviderTermsRoute
  '/Provider/withdraw': typeof ProviderWithdrawRoute
  '/book/$id': typeof BookIdRoute
  '/category/$name': typeof CategoryNameRoute
  '/companion/$id': typeof CompanionIdRoute
  '/Provider/': typeof ProviderIndexRoute
  '/Provider/auth/details': typeof ProviderAuthDetailsRoute
  '/Provider/auth/otp': typeof ProviderAuthOtpRoute
  '/Provider/auth/phone': typeof ProviderAuthPhoneRoute
  '/Provider/auth/pricing': typeof ProviderAuthPricingRoute
  '/Provider/auth/services': typeof ProviderAuthServicesRoute
  '/Provider/auth/verify': typeof ProviderAuthVerifyRoute
  '/Provider/booking/$id': typeof ProviderBookingIdRoute
  '/Provider/profile/preview': typeof ProviderProfilePreviewRoute
  '/Provider/session/complete': typeof ProviderSessionCompleteRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/chatbot': typeof ChatbotRoute
  '/confirmed': typeof ConfirmedRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/manage-addresses': typeof ManageAddressesRoute
  '/my-rating': typeof MyRatingRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/Provider/approval': typeof ProviderApprovalRoute
  '/Provider/availability': typeof ProviderAvailabilityRoute
  '/Provider/bank-accounts': typeof ProviderBankAccountsRoute
  '/Provider/blocked-customers': typeof ProviderBlockedCustomersRoute
  '/Provider/bookings': typeof ProviderBookingsRoute
  '/Provider/chat': typeof ProviderChatRoute
  '/Provider/code-of-conduct': typeof ProviderCodeOfConductRoute
  '/Provider/commission-details': typeof ProviderCommissionDetailsRoute
  '/Provider/earnings': typeof ProviderEarningsRoute
  '/Provider/emergency-contacts': typeof ProviderEmergencyContactsRoute
  '/Provider/feedback': typeof ProviderFeedbackRoute
  '/Provider/help-center': typeof ProviderHelpCenterRoute
  '/Provider/home': typeof ProviderHomeRoute
  '/Provider/more': typeof ProviderMoreRoute
  '/Provider/notifications': typeof ProviderNotificationsRoute
  '/Provider/performance': typeof ProviderPerformanceRoute
  '/Provider/privacy': typeof ProviderPrivacyRoute
  '/Provider/profile': typeof ProviderProfileRouteWithChildren
  '/Provider/reviews': typeof ProviderReviewsRoute
  '/Provider/safety-guidelines': typeof ProviderSafetyGuidelinesRoute
  '/Provider/session': typeof ProviderSessionRouteWithChildren
  '/Provider/splash': typeof ProviderSplashRoute
  '/Provider/terms': typeof ProviderTermsRoute
  '/Provider/withdraw': typeof ProviderWithdrawRoute
  '/book/$id': typeof BookIdRoute
  '/category/$name': typeof CategoryNameRoute
  '/companion/$id': typeof CompanionIdRoute
  '/Provider': typeof ProviderIndexRoute
  '/Provider/auth/details': typeof ProviderAuthDetailsRoute
  '/Provider/auth/otp': typeof ProviderAuthOtpRoute
  '/Provider/auth/phone': typeof ProviderAuthPhoneRoute
  '/Provider/auth/pricing': typeof ProviderAuthPricingRoute
  '/Provider/auth/services': typeof ProviderAuthServicesRoute
  '/Provider/auth/verify': typeof ProviderAuthVerifyRoute
  '/Provider/booking/$id': typeof ProviderBookingIdRoute
  '/Provider/profile/preview': typeof ProviderProfilePreviewRoute
  '/Provider/session/complete': typeof ProviderSessionCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/chatbot': typeof ChatbotRoute
  '/confirmed': typeof ConfirmedRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/manage-addresses': typeof ManageAddressesRoute
  '/my-rating': typeof MyRatingRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/Provider/approval': typeof ProviderApprovalRoute
  '/Provider/availability': typeof ProviderAvailabilityRoute
  '/Provider/bank-accounts': typeof ProviderBankAccountsRoute
  '/Provider/blocked-customers': typeof ProviderBlockedCustomersRoute
  '/Provider/bookings': typeof ProviderBookingsRoute
  '/Provider/chat': typeof ProviderChatRoute
  '/Provider/code-of-conduct': typeof ProviderCodeOfConductRoute
  '/Provider/commission-details': typeof ProviderCommissionDetailsRoute
  '/Provider/earnings': typeof ProviderEarningsRoute
  '/Provider/emergency-contacts': typeof ProviderEmergencyContactsRoute
  '/Provider/feedback': typeof ProviderFeedbackRoute
  '/Provider/help-center': typeof ProviderHelpCenterRoute
  '/Provider/home': typeof ProviderHomeRoute
  '/Provider/more': typeof ProviderMoreRoute
  '/Provider/notifications': typeof ProviderNotificationsRoute
  '/Provider/performance': typeof ProviderPerformanceRoute
  '/Provider/privacy': typeof ProviderPrivacyRoute
  '/Provider/profile': typeof ProviderProfileRouteWithChildren
  '/Provider/reviews': typeof ProviderReviewsRoute
  '/Provider/safety-guidelines': typeof ProviderSafetyGuidelinesRoute
  '/Provider/session': typeof ProviderSessionRouteWithChildren
  '/Provider/splash': typeof ProviderSplashRoute
  '/Provider/terms': typeof ProviderTermsRoute
  '/Provider/withdraw': typeof ProviderWithdrawRoute
  '/book/$id': typeof BookIdRoute
  '/category/$name': typeof CategoryNameRoute
  '/companion/$id': typeof CompanionIdRoute
  '/Provider/': typeof ProviderIndexRoute
  '/Provider/auth/details': typeof ProviderAuthDetailsRoute
  '/Provider/auth/otp': typeof ProviderAuthOtpRoute
  '/Provider/auth/phone': typeof ProviderAuthPhoneRoute
  '/Provider/auth/pricing': typeof ProviderAuthPricingRoute
  '/Provider/auth/services': typeof ProviderAuthServicesRoute
  '/Provider/auth/verify': typeof ProviderAuthVerifyRoute
  '/Provider/booking/$id': typeof ProviderBookingIdRoute
  '/Provider/profile/preview': typeof ProviderProfilePreviewRoute
  '/Provider/session/complete': typeof ProviderSessionCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/chatbot'
    | '/confirmed'
    | '/emergency'
    | '/explore'
    | '/faq'
    | '/home'
    | '/login'
    | '/manage-addresses'
    | '/my-rating'
    | '/notifications'
    | '/otp'
    | '/payment'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/session'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/Provider/approval'
    | '/Provider/availability'
    | '/Provider/bank-accounts'
    | '/Provider/blocked-customers'
    | '/Provider/bookings'
    | '/Provider/chat'
    | '/Provider/code-of-conduct'
    | '/Provider/commission-details'
    | '/Provider/earnings'
    | '/Provider/emergency-contacts'
    | '/Provider/feedback'
    | '/Provider/help-center'
    | '/Provider/home'
    | '/Provider/more'
    | '/Provider/notifications'
    | '/Provider/performance'
    | '/Provider/privacy'
    | '/Provider/profile'
    | '/Provider/reviews'
    | '/Provider/safety-guidelines'
    | '/Provider/session'
    | '/Provider/splash'
    | '/Provider/terms'
    | '/Provider/withdraw'
    | '/book/$id'
    | '/category/$name'
    | '/companion/$id'
    | '/Provider/'
    | '/Provider/auth/details'
    | '/Provider/auth/otp'
    | '/Provider/auth/phone'
    | '/Provider/auth/pricing'
    | '/Provider/auth/services'
    | '/Provider/auth/verify'
    | '/Provider/booking/$id'
    | '/Provider/profile/preview'
    | '/Provider/session/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/chatbot'
    | '/confirmed'
    | '/emergency'
    | '/explore'
    | '/faq'
    | '/home'
    | '/login'
    | '/manage-addresses'
    | '/my-rating'
    | '/notifications'
    | '/otp'
    | '/payment'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/session'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/Provider/approval'
    | '/Provider/availability'
    | '/Provider/bank-accounts'
    | '/Provider/blocked-customers'
    | '/Provider/bookings'
    | '/Provider/chat'
    | '/Provider/code-of-conduct'
    | '/Provider/commission-details'
    | '/Provider/earnings'
    | '/Provider/emergency-contacts'
    | '/Provider/feedback'
    | '/Provider/help-center'
    | '/Provider/home'
    | '/Provider/more'
    | '/Provider/notifications'
    | '/Provider/performance'
    | '/Provider/privacy'
    | '/Provider/profile'
    | '/Provider/reviews'
    | '/Provider/safety-guidelines'
    | '/Provider/session'
    | '/Provider/splash'
    | '/Provider/terms'
    | '/Provider/withdraw'
    | '/book/$id'
    | '/category/$name'
    | '/companion/$id'
    | '/Provider'
    | '/Provider/auth/details'
    | '/Provider/auth/otp'
    | '/Provider/auth/phone'
    | '/Provider/auth/pricing'
    | '/Provider/auth/services'
    | '/Provider/auth/verify'
    | '/Provider/booking/$id'
    | '/Provider/profile/preview'
    | '/Provider/session/complete'
  id:
    | '__root__'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/chatbot'
    | '/confirmed'
    | '/emergency'
    | '/explore'
    | '/faq'
    | '/home'
    | '/login'
    | '/manage-addresses'
    | '/my-rating'
    | '/notifications'
    | '/otp'
    | '/payment'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/session'
    | '/settings'
    | '/terms'
    | '/wallet'
    | '/Provider/approval'
    | '/Provider/availability'
    | '/Provider/bank-accounts'
    | '/Provider/blocked-customers'
    | '/Provider/bookings'
    | '/Provider/chat'
    | '/Provider/code-of-conduct'
    | '/Provider/commission-details'
    | '/Provider/earnings'
    | '/Provider/emergency-contacts'
    | '/Provider/feedback'
    | '/Provider/help-center'
    | '/Provider/home'
    | '/Provider/more'
    | '/Provider/notifications'
    | '/Provider/performance'
    | '/Provider/privacy'
    | '/Provider/profile'
    | '/Provider/reviews'
    | '/Provider/safety-guidelines'
    | '/Provider/session'
    | '/Provider/splash'
    | '/Provider/terms'
    | '/Provider/withdraw'
    | '/book/$id'
    | '/category/$name'
    | '/companion/$id'
    | '/Provider/'
    | '/Provider/auth/details'
    | '/Provider/auth/otp'
    | '/Provider/auth/phone'
    | '/Provider/auth/pricing'
    | '/Provider/auth/services'
    | '/Provider/auth/verify'
    | '/Provider/booking/$id'
    | '/Provider/profile/preview'
    | '/Provider/session/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRoute
  ChatbotRoute: typeof ChatbotRoute
  ConfirmedRoute: typeof ConfirmedRoute
  EmergencyRoute: typeof EmergencyRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ManageAddressesRoute: typeof ManageAddressesRoute
  MyRatingRoute: typeof MyRatingRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  ProviderApprovalRoute: typeof ProviderApprovalRoute
  ProviderAvailabilityRoute: typeof ProviderAvailabilityRoute
  ProviderBankAccountsRoute: typeof ProviderBankAccountsRoute
  ProviderBlockedCustomersRoute: typeof ProviderBlockedCustomersRoute
  ProviderBookingsRoute: typeof ProviderBookingsRoute
  ProviderChatRoute: typeof ProviderChatRoute
  ProviderCodeOfConductRoute: typeof ProviderCodeOfConductRoute
  ProviderCommissionDetailsRoute: typeof ProviderCommissionDetailsRoute
  ProviderEarningsRoute: typeof ProviderEarningsRoute
  ProviderEmergencyContactsRoute: typeof ProviderEmergencyContactsRoute
  ProviderFeedbackRoute: typeof ProviderFeedbackRoute
  ProviderHelpCenterRoute: typeof ProviderHelpCenterRoute
  ProviderHomeRoute: typeof ProviderHomeRoute
  ProviderMoreRoute: typeof ProviderMoreRoute
  ProviderNotificationsRoute: typeof ProviderNotificationsRoute
  ProviderPerformanceRoute: typeof ProviderPerformanceRoute
  ProviderPrivacyRoute: typeof ProviderPrivacyRoute
  ProviderProfileRoute: typeof ProviderProfileRouteWithChildren
  ProviderReviewsRoute: typeof ProviderReviewsRoute
  ProviderSafetyGuidelinesRoute: typeof ProviderSafetyGuidelinesRoute
  ProviderSessionRoute: typeof ProviderSessionRouteWithChildren
  ProviderSplashRoute: typeof ProviderSplashRoute
  ProviderTermsRoute: typeof ProviderTermsRoute
  ProviderWithdrawRoute: typeof ProviderWithdrawRoute
  BookIdRoute: typeof BookIdRoute
  CategoryNameRoute: typeof CategoryNameRoute
  CompanionIdRoute: typeof CompanionIdRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
  ProviderAuthDetailsRoute: typeof ProviderAuthDetailsRoute
  ProviderAuthOtpRoute: typeof ProviderAuthOtpRoute
  ProviderAuthPhoneRoute: typeof ProviderAuthPhoneRoute
  ProviderAuthPricingRoute: typeof ProviderAuthPricingRoute
  ProviderAuthServicesRoute: typeof ProviderAuthServicesRoute
  ProviderAuthVerifyRoute: typeof ProviderAuthVerifyRoute
  ProviderBookingIdRoute: typeof ProviderBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rating': {
      id: '/my-rating'
      path: '/my-rating'
      fullPath: '/my-rating'
      preLoaderRoute: typeof MyRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-addresses': {
      id: '/manage-addresses'
      path: '/manage-addresses'
      fullPath: '/manage-addresses'
      preLoaderRoute: typeof ManageAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/': {
      id: '/Provider/'
      path: '/Provider'
      fullPath: '/Provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion/$id': {
      id: '/companion/$id'
      path: '/companion/$id'
      fullPath: '/companion/$id'
      preLoaderRoute: typeof CompanionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/withdraw': {
      id: '/Provider/withdraw'
      path: '/Provider/withdraw'
      fullPath: '/Provider/withdraw'
      preLoaderRoute: typeof ProviderWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/terms': {
      id: '/Provider/terms'
      path: '/Provider/terms'
      fullPath: '/Provider/terms'
      preLoaderRoute: typeof ProviderTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/splash': {
      id: '/Provider/splash'
      path: '/Provider/splash'
      fullPath: '/Provider/splash'
      preLoaderRoute: typeof ProviderSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/session': {
      id: '/Provider/session'
      path: '/Provider/session'
      fullPath: '/Provider/session'
      preLoaderRoute: typeof ProviderSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/safety-guidelines': {
      id: '/Provider/safety-guidelines'
      path: '/Provider/safety-guidelines'
      fullPath: '/Provider/safety-guidelines'
      preLoaderRoute: typeof ProviderSafetyGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/reviews': {
      id: '/Provider/reviews'
      path: '/Provider/reviews'
      fullPath: '/Provider/reviews'
      preLoaderRoute: typeof ProviderReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/profile': {
      id: '/Provider/profile'
      path: '/Provider/profile'
      fullPath: '/Provider/profile'
      preLoaderRoute: typeof ProviderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/privacy': {
      id: '/Provider/privacy'
      path: '/Provider/privacy'
      fullPath: '/Provider/privacy'
      preLoaderRoute: typeof ProviderPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/performance': {
      id: '/Provider/performance'
      path: '/Provider/performance'
      fullPath: '/Provider/performance'
      preLoaderRoute: typeof ProviderPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/notifications': {
      id: '/Provider/notifications'
      path: '/Provider/notifications'
      fullPath: '/Provider/notifications'
      preLoaderRoute: typeof ProviderNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/more': {
      id: '/Provider/more'
      path: '/Provider/more'
      fullPath: '/Provider/more'
      preLoaderRoute: typeof ProviderMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/home': {
      id: '/Provider/home'
      path: '/Provider/home'
      fullPath: '/Provider/home'
      preLoaderRoute: typeof ProviderHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/help-center': {
      id: '/Provider/help-center'
      path: '/Provider/help-center'
      fullPath: '/Provider/help-center'
      preLoaderRoute: typeof ProviderHelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/feedback': {
      id: '/Provider/feedback'
      path: '/Provider/feedback'
      fullPath: '/Provider/feedback'
      preLoaderRoute: typeof ProviderFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/emergency-contacts': {
      id: '/Provider/emergency-contacts'
      path: '/Provider/emergency-contacts'
      fullPath: '/Provider/emergency-contacts'
      preLoaderRoute: typeof ProviderEmergencyContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/earnings': {
      id: '/Provider/earnings'
      path: '/Provider/earnings'
      fullPath: '/Provider/earnings'
      preLoaderRoute: typeof ProviderEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/commission-details': {
      id: '/Provider/commission-details'
      path: '/Provider/commission-details'
      fullPath: '/Provider/commission-details'
      preLoaderRoute: typeof ProviderCommissionDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/code-of-conduct': {
      id: '/Provider/code-of-conduct'
      path: '/Provider/code-of-conduct'
      fullPath: '/Provider/code-of-conduct'
      preLoaderRoute: typeof ProviderCodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/chat': {
      id: '/Provider/chat'
      path: '/Provider/chat'
      fullPath: '/Provider/chat'
      preLoaderRoute: typeof ProviderChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/bookings': {
      id: '/Provider/bookings'
      path: '/Provider/bookings'
      fullPath: '/Provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/blocked-customers': {
      id: '/Provider/blocked-customers'
      path: '/Provider/blocked-customers'
      fullPath: '/Provider/blocked-customers'
      preLoaderRoute: typeof ProviderBlockedCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/bank-accounts': {
      id: '/Provider/bank-accounts'
      path: '/Provider/bank-accounts'
      fullPath: '/Provider/bank-accounts'
      preLoaderRoute: typeof ProviderBankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/availability': {
      id: '/Provider/availability'
      path: '/Provider/availability'
      fullPath: '/Provider/availability'
      preLoaderRoute: typeof ProviderAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/approval': {
      id: '/Provider/approval'
      path: '/Provider/approval'
      fullPath: '/Provider/approval'
      preLoaderRoute: typeof ProviderApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/session/complete': {
      id: '/Provider/session/complete'
      path: '/complete'
      fullPath: '/Provider/session/complete'
      preLoaderRoute: typeof ProviderSessionCompleteRouteImport
      parentRoute: typeof ProviderSessionRoute
    }
    '/Provider/profile/preview': {
      id: '/Provider/profile/preview'
      path: '/preview'
      fullPath: '/Provider/profile/preview'
      preLoaderRoute: typeof ProviderProfilePreviewRouteImport
      parentRoute: typeof ProviderProfileRoute
    }
    '/Provider/booking/$id': {
      id: '/Provider/booking/$id'
      path: '/Provider/booking/$id'
      fullPath: '/Provider/booking/$id'
      preLoaderRoute: typeof ProviderBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/verify': {
      id: '/Provider/auth/verify'
      path: '/Provider/auth/verify'
      fullPath: '/Provider/auth/verify'
      preLoaderRoute: typeof ProviderAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/services': {
      id: '/Provider/auth/services'
      path: '/Provider/auth/services'
      fullPath: '/Provider/auth/services'
      preLoaderRoute: typeof ProviderAuthServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/pricing': {
      id: '/Provider/auth/pricing'
      path: '/Provider/auth/pricing'
      fullPath: '/Provider/auth/pricing'
      preLoaderRoute: typeof ProviderAuthPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/phone': {
      id: '/Provider/auth/phone'
      path: '/Provider/auth/phone'
      fullPath: '/Provider/auth/phone'
      preLoaderRoute: typeof ProviderAuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/otp': {
      id: '/Provider/auth/otp'
      path: '/Provider/auth/otp'
      fullPath: '/Provider/auth/otp'
      preLoaderRoute: typeof ProviderAuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Provider/auth/details': {
      id: '/Provider/auth/details'
      path: '/Provider/auth/details'
      fullPath: '/Provider/auth/details'
      preLoaderRoute: typeof ProviderAuthDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProviderProfileRouteChildren {
  ProviderProfilePreviewRoute: typeof ProviderProfilePreviewRoute
}

const ProviderProfileRouteChildren: ProviderProfileRouteChildren = {
  ProviderProfilePreviewRoute: ProviderProfilePreviewRoute,
}

const ProviderProfileRouteWithChildren = ProviderProfileRoute._addFileChildren(
  ProviderProfileRouteChildren,
)

interface ProviderSessionRouteChildren {
  ProviderSessionCompleteRoute: typeof ProviderSessionCompleteRoute
}

const ProviderSessionRouteChildren: ProviderSessionRouteChildren = {
  ProviderSessionCompleteRoute: ProviderSessionCompleteRoute,
}

const ProviderSessionRouteWithChildren = ProviderSessionRoute._addFileChildren(
  ProviderSessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRoute,
  ChatbotRoute: ChatbotRoute,
  ConfirmedRoute: ConfirmedRoute,
  EmergencyRoute: EmergencyRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ManageAddressesRoute: ManageAddressesRoute,
  MyRatingRoute: MyRatingRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  ProviderApprovalRoute: ProviderApprovalRoute,
  ProviderAvailabilityRoute: ProviderAvailabilityRoute,
  ProviderBankAccountsRoute: ProviderBankAccountsRoute,
  ProviderBlockedCustomersRoute: ProviderBlockedCustomersRoute,
  ProviderBookingsRoute: ProviderBookingsRoute,
  ProviderChatRoute: ProviderChatRoute,
  ProviderCodeOfConductRoute: ProviderCodeOfConductRoute,
  ProviderCommissionDetailsRoute: ProviderCommissionDetailsRoute,
  ProviderEarningsRoute: ProviderEarningsRoute,
  ProviderEmergencyContactsRoute: ProviderEmergencyContactsRoute,
  ProviderFeedbackRoute: ProviderFeedbackRoute,
  ProviderHelpCenterRoute: ProviderHelpCenterRoute,
  ProviderHomeRoute: ProviderHomeRoute,
  ProviderMoreRoute: ProviderMoreRoute,
  ProviderNotificationsRoute: ProviderNotificationsRoute,
  ProviderPerformanceRoute: ProviderPerformanceRoute,
  ProviderPrivacyRoute: ProviderPrivacyRoute,
  ProviderProfileRoute: ProviderProfileRouteWithChildren,
  ProviderReviewsRoute: ProviderReviewsRoute,
  ProviderSafetyGuidelinesRoute: ProviderSafetyGuidelinesRoute,
  ProviderSessionRoute: ProviderSessionRouteWithChildren,
  ProviderSplashRoute: ProviderSplashRoute,
  ProviderTermsRoute: ProviderTermsRoute,
  ProviderWithdrawRoute: ProviderWithdrawRoute,
  BookIdRoute: BookIdRoute,
  CategoryNameRoute: CategoryNameRoute,
  CompanionIdRoute: CompanionIdRoute,
  ProviderIndexRoute: ProviderIndexRoute,
  ProviderAuthDetailsRoute: ProviderAuthDetailsRoute,
  ProviderAuthOtpRoute: ProviderAuthOtpRoute,
  ProviderAuthPhoneRoute: ProviderAuthPhoneRoute,
  ProviderAuthPricingRoute: ProviderAuthPricingRoute,
  ProviderAuthServicesRoute: ProviderAuthServicesRoute,
  ProviderAuthVerifyRoute: ProviderAuthVerifyRoute,
  ProviderBookingIdRoute: ProviderBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
